flags: {}
extra-package-dbs: []
packages:
- 'deptrack-core'
- 'deptrack-devops'
- 'deptrack-devops-recipes'
- 'deptrack-devops-examples'
- location:
    git: 'https://github.com/abailly/hdo.git'
    commit: 'b2c365d'
  extra-dep: true
extra-deps:
- 'dotgen-0.4.2'
- 'http-querystring-1.0'
resolver: nightly-2017-10-13
